name: common
description: "The common package in the LevelUp App is a Dart package that centralizes all reusable widgets, components, constants, and utilities. It promotes modularity, consistency, and maintainability across the app while reducing duplicate development effort."

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.2
  emoji_picker_flutter: ^4.3.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true